# Generated by Django 4.2.3 on 2023-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='petsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(blank=True, max_length=20, null=True)),
                ('breed', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
