# Generated by Django 4.2.3 on 2023-08-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_servicedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsdb',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
