# Generated by Django 4.2.3 on 2023-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_petsdb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsdb',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
