# Generated by Django 4.2.3 on 2023-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_petsdb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='petsdb',
            name='description',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='servicedb',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
