# Generated by Django 4.2.3 on 2023-08-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_acceptdb_alter_petsdb_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptdb',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='acceptdb',
            name='date',
        ),
        migrations.RemoveField(
            model_name='acceptdb',
            name='email',
        ),
        migrations.RemoveField(
            model_name='acceptdb',
            name='purpose',
        ),
        migrations.AddField(
            model_name='acceptdb',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acceptdb',
            name='breed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
